name: CI - Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: unbuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.quangduc88 }}
          password: ${{ secrets.quangduc88 }}

    - name: Build & Push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: quangduc88/docker-ci-demo-latest

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.192.168.126.130 }}
        username: ${{ secrets.quangduc88 }}
        key: ${{ secrets.ssh-ed25519 AAAAC3NzaC1lZDl1NTE5AAAAIExpC60VfnZLC
        script: |
          cd ~/docker-ci-demo
          docker pull quangduc88/docker-ci-demo:latest
          docker compose up -d
