name: CI/CD - Build, Push & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags)
        id: meta
        run: |
          echo "tags=${{ secrets.DOCKER_USERNAME }}/ci-cd:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "tags=${{ secrets.DOCKER_USERNAME }}/ci-cd:latest" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ci-cd:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/ci-cd:latest

  deploy:
    name: SSH Deploy to Server
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH (pull latest and restart)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd ~/docker-ci-demo || exit 1
            # stop any existing containers that bind the same ports
            docker compose pull || true
            docker compose up -d --remove-orphans
            docker image prune -f || true
